alert('Brendan Eich создатель языка JavaScript')
alert('Известный прототип JavaScript был создан за 10 дней')
alert('JavaScript  появился в 1995 году')
alert('JavaScript - это не Java')
alert(' Спецификация языка JavaScript называется ECMAScriptt')
